---
apiVersion: v1
kind: Namespace
metadata:
   name: prashanth
---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp #very imp
  namespace: prashanth
spec:
  containers:
  - name: javaweappcontainer
    image: prashanth0108/taxi
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: prashanth
spec:
  type: NodePort
  selector:
    app: javawebapp  #POD label
  ports:
    - port: 80
      targetPort: 8080
...
